# Generated by Django 4.0.1 on 2022-01-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.IntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['model_type', 'is_complete', 'id'], name='issue_type_complete_id'),
        ),
    ]
