# Generated by Django 4.0.1 on 2022-01-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_issue_account'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='issue',
            name='issue_type_complete_id',
        ),
    ]
