# Generated by Django 4.0.1 on 2022-01-29 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('model_type', models.IntegerField(default=1)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='issue.issue')),
            ],
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['is_complete', 'id'], name='work_complete_id'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['model_type', 'is_complete', 'id'], name='work_type_complete_id'),
        ),
    ]
