# Generated by Django 4.0.1 on 2022-01-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummy',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
